recipe_db_query_tool = {
    "name": "query_food_recipe_vector_db",
    "description": """
  Queries the vector database containing food recipes to retrieve the most relevant documents. 
  This function allows the model to generate and execute multiple queries as necessary to gather comprehensive context,
  ensuring accurate and thorough responses to user queries specifically related to recipes.
  Each recipe document includes details such as name, description, recipe category, ingredients, instructions, cook time, 
  community rating, and review count
  """,
    "input_schema": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "array",
                "items": {
                    "type": "string",
                    "description": "A query generated by the model to run against the vector database to fetch recipe documents. This should be used to fetch specific recipes, ingredients, preparation steps, and related metadata.",
                },
                "description": "A list of queries generated by the model to run against the vector database to fetch recipe documents.",
            }
        },
        "required": ["queries"],
    },
}

# google_web_search_tool = {
#     "name": "google_web_search",
#     "description": """
#   Queries the Google web search engine to retrieve relevant information from the web.
#   This function allows the model to search for information it is unsure about, such as
#   ingredient substitutions, cooking techniques, nutritional information, or other specific
#   knowledge not contained within the recipe vector database, providing accurate and up-to-date
#   answers to user queries.
#   """,
#     "input_schema": {
#         "type": "object",
#         "properties": {
#             "queries": {
#                 "type": "array",
#                 "items": {
#                     "type": "string",
#                     "description": "A query generated by the model to search on Google for relevant information, particularly for details outside the scope of the recipe vector database, such as ingredient substitutions or cooking techniques.",
#                 },
#                 "description": "A list of queries generated by the model to search on Google for relevant information.",
#             }
#         },
#         "required": ["queries"],
#     },
# }
