recipe_db_query_tool = {
    "name": "query_food_recipe_vector_db",
    "description": """
      Queries the vector database containing food recipes to retrieve the most relevant documents. 
      This function allows the model to generate and execute multiple queries as necessary to gather comprehensive context, 
      such as ingredients, preparation steps, and metadata like cuisine and diet type, ensuring accurate and thorough responses to user queries.
      """,
    "input_schema": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "array",
                "items": {
                    "type": "string",
                    "description": "A query generated by the model to run against the vector database to fetch recipe documents.",
                },
                "description": "A list of queries generated by the model to run against the vector database to fetch recipe documents.",
            }
        },
        "required": ["queries"],
    },
}
